"""make counted_qty nullable and add unique constraint

Revision ID: 4885bf922008
Revises: 
Create Date: 2026-03-17 02:10:58.766803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4885bf922008'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stock_count_lines', 'counted_quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('stock_count_lines', 'variance',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint('uq_session_item', 'stock_count_lines', ['stock_count_session_id', 'item_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_session_item', 'stock_count_lines', type_='unique')
    op.alter_column('stock_count_lines', 'variance',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('stock_count_lines', 'counted_quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
